# Generated by Django 3.1.3 on 2021-04-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_wholesale_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
