# Generated by Django 3.1.3 on 2020-12-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_danpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danpost',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterIndexTogether(
            name='danpost',
            index_together={('id', 'slug')},
        ),
    ]
