# Generated by Django 3.1.3 on 2020-12-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codenum',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
