# Generated by Django 3.1.3 on 2020-12-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
