# Generated by Django 3.1.3 on 2020-11-06 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
