# Generated by Django 3.1.3 on 2021-04-20 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_product_wholesale_price'),
        ('orders', '0004_order_user_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='wh_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(default='0', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('braintree_id', models.CharField(blank=True, max_length=150)),
                ('user_order', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='wh_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش همکاران',
                'verbose_name_plural': 'سفارش های همکاران ',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='wh_OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.wh_order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_order_items', to='shop.product')),
            ],
        ),
    ]
